namespace SMSgroup.Aveva.Application.CLI.PGedge.Connector.Templates
{
    internal static class ConnectorScriptTemplate
    {
        /// <summary>
        /// Builds the final .cmd script.
        /// All arguments MUST be validated before calling.
        /// </summary>
        public static string Build(string inputCliPath, string inputConnectorName, string inputEvarName)
        {
            // VALIDATION
            if (string.IsNullOrWhiteSpace(inputCliPath))
                throw new ArgumentException("CLI path cannot be empty.", nameof(inputCliPath));

            if (string.IsNullOrWhiteSpace(inputConnectorName))
                throw new ArgumentException("Connector name cannot be empty.", nameof(inputConnectorName));

            if (string.IsNullOrWhiteSpace(inputEvarName))
                throw new ArgumentException("Environment variable name cannot be empty.", nameof(inputEvarName));

            var cliPath = inputCliPath.Replace('/', '\\').Trim();
            var connectorName = inputConnectorName.Trim();
            var evarName = inputEvarName.Trim();

            return
            $@"@echo off
            setlocal
            
            REM -----------------------------------------------------------
            REM  {connectorName} Connector Script
            REM  Generated by: pgedge connector publish
            REM  Sets {evarName} to point to the PGedge CLI executable.
            REM -----------------------------------------------------------
            
            set ""CLI_EXE={cliPath}""
            
            if not exist ""%CLI_EXE%"" (
                echo [ERROR] PGedge CLI not found at:
                echo   %CLI_EXE%
                echo.
                echo Please correct CLI_EXE in this script.
                echo.
                pause
                exit /b 1
            )
            
            echo.
            echo Running {connectorName} Connector...
            echo ----------------------------------------------
            echo Using CLI:
            echo   %CLI_EXE%
            echo.
            
            echo Setting environment variable: {evarName}
            echo.
            
            ""%CLI_EXE%"" pgedge env set --name {evarName} --value ""%CLI_EXE%""
            set ERR=%ERRORLEVEL%
            
            if %ERR% NEQ 0 (
                echo.
                echo [ERROR] pgedge env set failed! Exit code: %ERR%
                echo.
                pause
                exit /b %ERR%
            )
            
            echo.
            echo [OK] {evarName} is now set to:
            echo   %CLI_EXE%
            
            echo You may now use the WebApp Desktop Launcher.
            echo.
            pause
            ";
        }
    }
}
