using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace SMSgroup.Aveva.Application.CLI.PGedge.Connector.Templates
{
    /// <summary>
    /// Builds a launcher .cmd that runs the local WebApp (dotnet run) and opens the browser.
    /// </summary>
    public static class WebAppLauncherTemplate
    {
        /// <summary>
        /// Build the Run-WebApp.cmd file.
        /// webAppProjectPath: folder that contains the .csproj (or the .csproj path itself).
        /// </summary>
        public static string BuildRunCmd(
            string webAppProjectPath,
            string launchProfile,
            string webAppUrl)
        {
            if (string.IsNullOrWhiteSpace(webAppProjectPath))
                throw new ArgumentException("WebApp project path cannot be empty.", nameof(webAppProjectPath));

            if (string.IsNullOrWhiteSpace(launchProfile))
                launchProfile = "https";

            if (string.IsNullOrWhiteSpace(webAppUrl))
                webAppUrl = "https://localhost:7285";

            // Normalize backslashes, trim quotes
            var projectPath = webAppProjectPath.Trim().Trim('"').Replace('/', '\\');

            return
$@"@echo off
setlocal

REM -----------------------------------------------------------
REM  PGedge WebApp Launcher
REM  Generated by: pgedge connector publish
REM  Starts dotnet run and opens the WebApp in a browser.
REM -----------------------------------------------------------

set ""WEBAPP_PROJECT={projectPath}""
set ""WEBAPP_LAUNCH_PROFILE={launchProfile}""
set ""WEBAPP_URL={webAppUrl}""

echo [PGedge] Starting WebApp from ""%WEBAPP_PROJECT%"" (profile %WEBAPP_LAUNCH_PROFILE%)...

start ""PGedge WebApp"" cmd /k ""cd /d ""%WEBAPP_PROJECT%"" && dotnet run --launch-profile %WEBAPP_LAUNCH_PROFILE%""

REM Give Kestrel a moment to start; adjust if needed
timeout /t 5 /nobreak >nul

echo [PGedge] Opening %WEBAPP_URL% in the default browser...
start """" ""%WEBAPP_URL%""

endlocal
";
        }
    }
}
